// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartMonitorBidirectionalStream.proto

package heartMonitorBidirectionalStream;

public final class HeartMonitorBidirectionalStream {
  private HeartMonitorBidirectionalStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartRateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:heartMonitorBidirectionalStream.HeartRate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Current BPM
     * </pre>
     *
     * <code>int32 bpm = 1;</code>
     */
    int getBpm();
  }
  /**
   * Protobuf type {@code heartMonitorBidirectionalStream.HeartRate}
   */
  public  static final class HeartRate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heartMonitorBidirectionalStream.HeartRate)
      HeartRateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartRate.newBuilder() to construct.
    private HeartRate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartRate() {
      bpm_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartRate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bpm_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.class, heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.Builder.class);
    }

    public static final int BPM_FIELD_NUMBER = 1;
    private int bpm_;
    /**
     * <pre>
     * Current BPM
     * </pre>
     *
     * <code>int32 bpm = 1;</code>
     */
    public int getBpm() {
      return bpm_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bpm_ != 0) {
        output.writeInt32(1, bpm_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bpm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bpm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate)) {
        return super.equals(obj);
      }
      heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate other = (heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate) obj;

      boolean result = true;
      result = result && (getBpm()
          == other.getBpm());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BPM_FIELD_NUMBER;
      hash = (53 * hash) + getBpm();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heartMonitorBidirectionalStream.HeartRate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heartMonitorBidirectionalStream.HeartRate)
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.class, heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.Builder.class);
      }

      // Construct using heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bpm_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor;
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate getDefaultInstanceForType() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.getDefaultInstance();
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate build() {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate buildPartial() {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate result = new heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate(this);
        result.bpm_ = bpm_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate) {
          return mergeFrom((heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate other) {
        if (other == heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate.getDefaultInstance()) return this;
        if (other.getBpm() != 0) {
          setBpm(other.getBpm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bpm_ ;
      /**
       * <pre>
       * Current BPM
       * </pre>
       *
       * <code>int32 bpm = 1;</code>
       */
      public int getBpm() {
        return bpm_;
      }
      /**
       * <pre>
       * Current BPM
       * </pre>
       *
       * <code>int32 bpm = 1;</code>
       */
      public Builder setBpm(int value) {
        
        bpm_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Current BPM
       * </pre>
       *
       * <code>int32 bpm = 1;</code>
       */
      public Builder clearBpm() {
        
        bpm_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heartMonitorBidirectionalStream.HeartRate)
    }

    // @@protoc_insertion_point(class_scope:heartMonitorBidirectionalStream.HeartRate)
    private static final heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate();
    }

    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartRate>
        PARSER = new com.google.protobuf.AbstractParser<HeartRate>() {
      @java.lang.Override
      public HeartRate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartRate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartRate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartRate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartRateFeedbackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:heartMonitorBidirectionalStream.HeartRateFeedback)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Messages from the server
     * </pre>
     *
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Messages from the server
     * </pre>
     *
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code heartMonitorBidirectionalStream.HeartRateFeedback}
   */
  public  static final class HeartRateFeedback extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heartMonitorBidirectionalStream.HeartRateFeedback)
      HeartRateFeedbackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartRateFeedback.newBuilder() to construct.
    private HeartRateFeedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartRateFeedback() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartRateFeedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.class, heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Messages from the server
     * </pre>
     *
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Messages from the server
     * </pre>
     *
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback)) {
        return super.equals(obj);
      }
      heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback other = (heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heartMonitorBidirectionalStream.HeartRateFeedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heartMonitorBidirectionalStream.HeartRateFeedback)
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.class, heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.Builder.class);
      }

      // Construct using heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor;
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback getDefaultInstanceForType() {
        return heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.getDefaultInstance();
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback build() {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback buildPartial() {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback result = new heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback) {
          return mergeFrom((heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback other) {
        if (other == heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Messages from the server
       * </pre>
       *
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Messages from the server
       * </pre>
       *
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Messages from the server
       * </pre>
       *
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Messages from the server
       * </pre>
       *
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Messages from the server
       * </pre>
       *
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heartMonitorBidirectionalStream.HeartRateFeedback)
    }

    // @@protoc_insertion_point(class_scope:heartMonitorBidirectionalStream.HeartRateFeedback)
    private static final heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback();
    }

    public static heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartRateFeedback>
        PARSER = new com.google.protobuf.AbstractParser<HeartRateFeedback>() {
      @java.lang.Override
      public HeartRateFeedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartRateFeedback(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartRateFeedback> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartRateFeedback> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public heartMonitorBidirectionalStream.HeartMonitorBidirectionalStream.HeartRateFeedback getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heartMonitorBidirectionalStream_HeartRate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%heartMonitorBidirectionalStream.proto\022" +
      "\037heartMonitorBidirectionalStream\"\030\n\tHear" +
      "tRate\022\013\n\003bpm\030\001 \001(\005\"$\n\021HeartRateFeedback\022" +
      "\017\n\007message\030\001 \001(\t2\213\001\n\021SmartWatchService\022v" +
      "\n\020monitorHeartRate\022*.heartMonitorBidirec" +
      "tionalStream.HeartRate\0322.heartMonitorBid" +
      "irectionalStream.HeartRateFeedback(\0010\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heartMonitorBidirectionalStream_HeartRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heartMonitorBidirectionalStream_HeartRate_descriptor,
        new java.lang.String[] { "Bpm", });
    internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heartMonitorBidirectionalStream_HeartRateFeedback_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
