// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobileAppServerStream.proto

package mobileAppServerStream;

public final class MobileAppServerStream {
  private MobileAppServerStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HydrationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mobileAppServerStream.HydrationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * User preferred interval between reminders
     * </pre>
     *
     * <code>int32 interval_minutes = 1;</code>
     */
    int getIntervalMinutes();
  }
  /**
   * Protobuf type {@code mobileAppServerStream.HydrationRequest}
   */
  public  static final class HydrationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mobileAppServerStream.HydrationRequest)
      HydrationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HydrationRequest.newBuilder() to construct.
    private HydrationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HydrationRequest() {
      intervalMinutes_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HydrationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              intervalMinutes_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mobileAppServerStream.MobileAppServerStream.HydrationRequest.class, mobileAppServerStream.MobileAppServerStream.HydrationRequest.Builder.class);
    }

    public static final int INTERVAL_MINUTES_FIELD_NUMBER = 1;
    private int intervalMinutes_;
    /**
     * <pre>
     * User preferred interval between reminders
     * </pre>
     *
     * <code>int32 interval_minutes = 1;</code>
     */
    public int getIntervalMinutes() {
      return intervalMinutes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intervalMinutes_ != 0) {
        output.writeInt32(1, intervalMinutes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intervalMinutes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intervalMinutes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mobileAppServerStream.MobileAppServerStream.HydrationRequest)) {
        return super.equals(obj);
      }
      mobileAppServerStream.MobileAppServerStream.HydrationRequest other = (mobileAppServerStream.MobileAppServerStream.HydrationRequest) obj;

      boolean result = true;
      result = result && (getIntervalMinutes()
          == other.getIntervalMinutes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERVAL_MINUTES_FIELD_NUMBER;
      hash = (53 * hash) + getIntervalMinutes();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mobileAppServerStream.MobileAppServerStream.HydrationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mobileAppServerStream.HydrationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mobileAppServerStream.HydrationRequest)
        mobileAppServerStream.MobileAppServerStream.HydrationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mobileAppServerStream.MobileAppServerStream.HydrationRequest.class, mobileAppServerStream.MobileAppServerStream.HydrationRequest.Builder.class);
      }

      // Construct using mobileAppServerStream.MobileAppServerStream.HydrationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intervalMinutes_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationRequest_descriptor;
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationRequest getDefaultInstanceForType() {
        return mobileAppServerStream.MobileAppServerStream.HydrationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationRequest build() {
        mobileAppServerStream.MobileAppServerStream.HydrationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationRequest buildPartial() {
        mobileAppServerStream.MobileAppServerStream.HydrationRequest result = new mobileAppServerStream.MobileAppServerStream.HydrationRequest(this);
        result.intervalMinutes_ = intervalMinutes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobileAppServerStream.MobileAppServerStream.HydrationRequest) {
          return mergeFrom((mobileAppServerStream.MobileAppServerStream.HydrationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mobileAppServerStream.MobileAppServerStream.HydrationRequest other) {
        if (other == mobileAppServerStream.MobileAppServerStream.HydrationRequest.getDefaultInstance()) return this;
        if (other.getIntervalMinutes() != 0) {
          setIntervalMinutes(other.getIntervalMinutes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mobileAppServerStream.MobileAppServerStream.HydrationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mobileAppServerStream.MobileAppServerStream.HydrationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int intervalMinutes_ ;
      /**
       * <pre>
       * User preferred interval between reminders
       * </pre>
       *
       * <code>int32 interval_minutes = 1;</code>
       */
      public int getIntervalMinutes() {
        return intervalMinutes_;
      }
      /**
       * <pre>
       * User preferred interval between reminders
       * </pre>
       *
       * <code>int32 interval_minutes = 1;</code>
       */
      public Builder setIntervalMinutes(int value) {
        
        intervalMinutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * User preferred interval between reminders
       * </pre>
       *
       * <code>int32 interval_minutes = 1;</code>
       */
      public Builder clearIntervalMinutes() {
        
        intervalMinutes_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mobileAppServerStream.HydrationRequest)
    }

    // @@protoc_insertion_point(class_scope:mobileAppServerStream.HydrationRequest)
    private static final mobileAppServerStream.MobileAppServerStream.HydrationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mobileAppServerStream.MobileAppServerStream.HydrationRequest();
    }

    public static mobileAppServerStream.MobileAppServerStream.HydrationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HydrationRequest>
        PARSER = new com.google.protobuf.AbstractParser<HydrationRequest>() {
      @java.lang.Override
      public HydrationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HydrationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HydrationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HydrationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mobileAppServerStream.MobileAppServerStream.HydrationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HydrationNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mobileAppServerStream.HydrationNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Timestamp of the reminder
     * </pre>
     *
     * <code>int32 timestamp = 1;</code>
     */
    int getTimestamp();

    /**
     * <pre>
     * Reminder message
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Reminder message
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code mobileAppServerStream.HydrationNotification}
   */
  public  static final class HydrationNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mobileAppServerStream.HydrationNotification)
      HydrationNotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HydrationNotification.newBuilder() to construct.
    private HydrationNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HydrationNotification() {
      timestamp_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HydrationNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationNotification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mobileAppServerStream.MobileAppServerStream.HydrationNotification.class, mobileAppServerStream.MobileAppServerStream.HydrationNotification.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <pre>
     * Timestamp of the reminder
     * </pre>
     *
     * <code>int32 timestamp = 1;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Reminder message
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Reminder message
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0) {
        output.writeInt32(1, timestamp_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timestamp_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mobileAppServerStream.MobileAppServerStream.HydrationNotification)) {
        return super.equals(obj);
      }
      mobileAppServerStream.MobileAppServerStream.HydrationNotification other = (mobileAppServerStream.MobileAppServerStream.HydrationNotification) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mobileAppServerStream.MobileAppServerStream.HydrationNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mobileAppServerStream.HydrationNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mobileAppServerStream.HydrationNotification)
        mobileAppServerStream.MobileAppServerStream.HydrationNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationNotification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mobileAppServerStream.MobileAppServerStream.HydrationNotification.class, mobileAppServerStream.MobileAppServerStream.HydrationNotification.Builder.class);
      }

      // Construct using mobileAppServerStream.MobileAppServerStream.HydrationNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobileAppServerStream.MobileAppServerStream.internal_static_mobileAppServerStream_HydrationNotification_descriptor;
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationNotification getDefaultInstanceForType() {
        return mobileAppServerStream.MobileAppServerStream.HydrationNotification.getDefaultInstance();
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationNotification build() {
        mobileAppServerStream.MobileAppServerStream.HydrationNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mobileAppServerStream.MobileAppServerStream.HydrationNotification buildPartial() {
        mobileAppServerStream.MobileAppServerStream.HydrationNotification result = new mobileAppServerStream.MobileAppServerStream.HydrationNotification(this);
        result.timestamp_ = timestamp_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobileAppServerStream.MobileAppServerStream.HydrationNotification) {
          return mergeFrom((mobileAppServerStream.MobileAppServerStream.HydrationNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mobileAppServerStream.MobileAppServerStream.HydrationNotification other) {
        if (other == mobileAppServerStream.MobileAppServerStream.HydrationNotification.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mobileAppServerStream.MobileAppServerStream.HydrationNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mobileAppServerStream.MobileAppServerStream.HydrationNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int timestamp_ ;
      /**
       * <pre>
       * Timestamp of the reminder
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * Timestamp of the reminder
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       */
      public Builder setTimestamp(int value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp of the reminder
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Reminder message
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Reminder message
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Reminder message
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reminder message
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reminder message
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mobileAppServerStream.HydrationNotification)
    }

    // @@protoc_insertion_point(class_scope:mobileAppServerStream.HydrationNotification)
    private static final mobileAppServerStream.MobileAppServerStream.HydrationNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mobileAppServerStream.MobileAppServerStream.HydrationNotification();
    }

    public static mobileAppServerStream.MobileAppServerStream.HydrationNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HydrationNotification>
        PARSER = new com.google.protobuf.AbstractParser<HydrationNotification>() {
      @java.lang.Override
      public HydrationNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HydrationNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HydrationNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HydrationNotification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mobileAppServerStream.MobileAppServerStream.HydrationNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobileAppServerStream_HydrationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobileAppServerStream_HydrationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobileAppServerStream_HydrationNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobileAppServerStream_HydrationNotification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mobileAppServerStream.proto\022\025mobileApp" +
      "ServerStream\",\n\020HydrationRequest\022\030\n\020inte" +
      "rval_minutes\030\001 \001(\005\";\n\025HydrationNotificat" +
      "ion\022\021\n\ttimestamp\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2" +
      "\200\001\n\020MobileAppService\022l\n\021hydrationReminde" +
      "r\022\'.mobileAppServerStream.HydrationReque" +
      "st\032,.mobileAppServerStream.HydrationNoti" +
      "fication0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mobileAppServerStream_HydrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mobileAppServerStream_HydrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobileAppServerStream_HydrationRequest_descriptor,
        new java.lang.String[] { "IntervalMinutes", });
    internal_static_mobileAppServerStream_HydrationNotification_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mobileAppServerStream_HydrationNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobileAppServerStream_HydrationNotification_descriptor,
        new java.lang.String[] { "Timestamp", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
