package GUI;

import heartMonitorBidirectionalStream.HeartRateClient;
import heartMonitorBidirectionalStream.HeartRateServer;

import javax.swing.*;

public class GUIHeartMonitor extends javax.swing.JPanel {
    private boolean isServerRunning = false;
    private boolean isCkientRunning = false;
    
    public GUIHeartMonitor() {
        initComponents();
    }

    private java.io.PrintStream getPrintStreamFor(JTextArea area) {
        return new java.io.PrintStream(new java.io.OutputStream() {
            private StringBuilder buffer = new StringBuilder();

            @Override
            public void write(int b) {
                if (b == '\n') {
                    String line = buffer.toString();
                    buffer.setLength(0);
                    SwingUtilities.invokeLater(() -> area.append(line + "\n"));
                } else {
                    buffer.append((char) b);
                }
            }
        }, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startServerHeartMonitor = new javax.swing.JButton();
        startClientHeartMonitor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaHeartMonitorServer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaHeartMonitorClient = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        interruptBidirectionalStreamButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Heart Monitor - Bidirectional Stream");

        startServerHeartMonitor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startServerHeartMonitor.setText("Start Server");
        startServerHeartMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerHeartMonitorActionPerformed(evt);
            }
        });

        startClientHeartMonitor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startClientHeartMonitor.setText("Start Client");
        startClientHeartMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientHeartMonitorActionPerformed(evt);
            }
        });

        textAreaHeartMonitorServer.setColumns(20);
        textAreaHeartMonitorServer.setRows(5);
        jScrollPane1.setViewportView(textAreaHeartMonitorServer);

        textAreaHeartMonitorClient.setColumns(20);
        textAreaHeartMonitorClient.setRows(5);
        jScrollPane2.setViewportView(textAreaHeartMonitorClient);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("There is a 3 seconds delay just to make sure that service is registered");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Stream will continue for 30 iterations unless user presses the button \"interrupt stream\"");

        interruptBidirectionalStreamButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        interruptBidirectionalStreamButton.setText("Interrupt stream");
        interruptBidirectionalStreamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interruptBidirectionalStreamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(425, 425, 425))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startServerHeartMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(startClientHeartMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(interruptBidirectionalStreamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(startServerHeartMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startClientHeartMonitor)
                    .addComponent(interruptBidirectionalStreamButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startServerHeartMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerHeartMonitorActionPerformed
        if (isServerRunning) {
            return; 
        }
        isServerRunning = true;
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaHeartMonitorServer));
            System.setErr(getPrintStreamFor(textAreaHeartMonitorServer));

            try {
                HeartRateServer.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }//GEN-LAST:event_startServerHeartMonitorActionPerformed

    private void startClientHeartMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClientHeartMonitorActionPerformed
        if (!isServerRunning) {
            JOptionPane.showMessageDialog(this, "Cannot start client: Server is not running.");
            return;
        }
        isCkientRunning = true;
        stopStreamGUI = false;
        
        textAreaHeartMonitorClient.append("Waiting service to be discovered...");
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaHeartMonitorClient));
            System.setErr(getPrintStreamFor(textAreaHeartMonitorClient));
            try {
                HeartRateClient.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }//GEN-LAST:event_startClientHeartMonitorActionPerformed

    public static boolean stopStreamGUI = false;
    private void interruptBidirectionalStreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interruptBidirectionalStreamButtonActionPerformed
        if (!isServerRunning) {
            JOptionPane.showMessageDialog(this, "Cannot interrupt client: Server is not running.");
            return;
        }
        
        if(!isCkientRunning){
            JOptionPane.showMessageDialog(this, "Please start the stream first");
            return;
        }
        
        stopStreamGUI = true;
        textAreaHeartMonitorClient.append("Stream interruption requested by user");
    }//GEN-LAST:event_interruptBidirectionalStreamButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton interruptBidirectionalStreamButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton startClientHeartMonitor;
    private javax.swing.JButton startServerHeartMonitor;
    private javax.swing.JTextArea textAreaHeartMonitorClient;
    private javax.swing.JTextArea textAreaHeartMonitorServer;
    // End of variables declaration//GEN-END:variables
}
