package GUI;

import smartCarUnary.SmartCarClient;
import smartCarUnary.SmartCarServer;

import javax.swing.*;

public class GUISmartCar extends javax.swing.JPanel {
    private boolean isServerRunning = false;
    
public GUISmartCar() {
        initComponents();
    }

    private java.io.PrintStream getPrintStreamFor(JTextArea area) {
        return new java.io.PrintStream(new java.io.OutputStream() {
            private StringBuilder buffer = new StringBuilder();

            @Override
            public void write(int b) {
                if (b == '\n') {
                    String line = buffer.toString();
                    buffer.setLength(0);
                    SwingUtilities.invokeLater(() -> area.append(line + "\n"));
                } else {
                    buffer.append((char) b);
                }
            }
        }, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startServerButtonSmartCar = new javax.swing.JButton();
        startClientButtonSmartCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSmartCarServer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaSmartCarClient = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        severityTextField = new javax.swing.JTextField();
        severityButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        startServerButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startServerButtonSmartCar.setText("Start Server");
        startServerButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonSmartCarActionPerformed(evt);
            }
        });

        startClientButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startClientButtonSmartCar.setText("Simulate Accident");
        startClientButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientButtonSmartCarActionPerformed(evt);
            }
        });

        textAreaSmartCarServer.setColumns(20);
        textAreaSmartCarServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarServer.setRows(5);
        jScrollPane1.setViewportView(textAreaSmartCarServer);

        textAreaSmartCarClient.setColumns(20);
        textAreaSmartCarClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarClient.setRows(5);
        jScrollPane2.setViewportView(textAreaSmartCarClient);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Smart Car - Unary service");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Please, enter severity (a number between 1 and 10) ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("If this field is empty, the number will be randomly generated");

        severityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityTextFieldActionPerformed(evt);
            }
        });

        severityButton.setText("Submit");
        severityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("There is a 3 seconds delay just to make sure that service is registered");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startClientButtonSmartCar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(startServerButtonSmartCar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(462, 462, 462)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(severityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(severityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(severityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(severityButton))
                .addGap(56, 56, 56)
                .addComponent(startServerButtonSmartCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startClientButtonSmartCar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void severityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityTextFieldActionPerformed

    private Integer userSeverity = null;
    private void severityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityButtonActionPerformed
        String input = severityTextField.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No severity entered. It will be randomly generated by the client.");
            SmartCarClient.severityFromGUI = null; 
        } else {
            try {
                int userSeverity = Integer.parseInt(input);

                if (userSeverity >= 1 && userSeverity <= 10) {
                    JOptionPane.showMessageDialog(this, "Number has been set: " + userSeverity);
                    SmartCarClient.severityFromGUI = userSeverity; 
                } else {
                    JOptionPane.showMessageDialog(this, "Number will be randomly generated");
                    SmartCarClient.severityFromGUI = null;
                }
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Number will be randomly generated");
                SmartCarClient.severityFromGUI = null;
            }
        }
    }//GEN-LAST:event_severityButtonActionPerformed

    private void startServerButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning) {
            return; 
        }
        isServerRunning = true;
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarServer));
            System.setErr(getPrintStreamFor(textAreaSmartCarServer));
            try {
                SmartCarServer.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    private void startClientButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isServerRunning) {
            JOptionPane.showMessageDialog(this, "Cannot start client: Server is not running.");
            return;
        }

        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarClient));
            System.setErr(getPrintStreamFor(textAreaSmartCarClient));
            try {
                SmartCarClient.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton severityButton;
    private javax.swing.JTextField severityTextField;
    private javax.swing.JButton startClientButtonSmartCar;
    private javax.swing.JButton startServerButtonSmartCar;
    private javax.swing.JTextArea textAreaSmartCarClient;
    private javax.swing.JTextArea textAreaSmartCarServer;
    // End of variables declaration//GEN-END:variables
}
