package GUI;

import smartCarUnary.SmartCarClient;
import smartCarUnary.SmartCarServer;

import javax.swing.*;

public class GUISmartCar extends javax.swing.JPanel {
    private boolean isServerRunning = false;
 
public GUISmartCar() {
        initComponents();
    }

    private java.io.PrintStream getPrintStreamFor(JTextArea area) {
        return new java.io.PrintStream(new java.io.OutputStream() {
            private StringBuilder buffer = new StringBuilder();

            @Override
            public void write(int b) {
                if (b == '\n') {
                    String line = buffer.toString();
                    buffer.setLength(0);
                    SwingUtilities.invokeLater(() -> area.append(line + "\n"));
                } else {
                    buffer.append((char) b);
                }
            }
        }, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startServerButtonSmartCar = new javax.swing.JButton();
        startClientButtonSmartCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSmartCarServer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaSmartCarClient = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        severityTextField = new javax.swing.JTextField();
        severityButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        simulateEmptyStatusButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        startServerButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startServerButtonSmartCar.setText("Start Server");
        startServerButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonSmartCarActionPerformed(evt);
            }
        });

        startClientButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startClientButtonSmartCar.setText("Simulate Accident");
        startClientButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientButtonSmartCarActionPerformed(evt);
            }
        });

        textAreaSmartCarServer.setColumns(20);
        textAreaSmartCarServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarServer.setRows(5);
        jScrollPane1.setViewportView(textAreaSmartCarServer);

        textAreaSmartCarClient.setColumns(20);
        textAreaSmartCarClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarClient.setRows(5);
        jScrollPane2.setViewportView(textAreaSmartCarClient);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Smart Car - Unary service");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Please, enter severity (a number between 1 and 10) ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("If this field is empty or input is invalid, the number will be randomly generated");

        severityTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        severityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityTextFieldActionPerformed(evt);
            }
        });

        severityButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        severityButton.setText("Submit");
        severityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("There is a 3 seconds delay just to make sure that service is registered");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Service Description:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("When a car accident happens, Client sends a request (right now it is just a number that can be either generated randomly or set by a user, but in reality it might be a sensors data, ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("depending on which different severity level is assigned (Serious or Minor). When Client is started, the number is sent to server as welll as all other data: location, time, severity. ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("After that server sends back the response and depending on severity either informes emergency services or asks user if they want server to call emergency");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("1. Start the server");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("2. Enter and Submit a severity number (if empty or wrong input - random will be generated)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("3. Start the Client (simulate response)");

        simulateEmptyStatusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        simulateEmptyStatusButton.setText("Simulate empty \"Status\"");
        simulateEmptyStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateEmptyStatusButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("4. Simulate empty \"Status\" string (optional)");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("If \"Status\" is empty, will throw a remote error");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Button \"Simulate empty status\" will make status (Serious or Minor) empty, so the error will be thrown. The number can be submitted / resubmitted at any stage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startClientButtonSmartCar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(simulateEmptyStatusButton)
                            .addComponent(jLabel13))
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(severityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(severityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10))))
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startServerButtonSmartCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startServerButtonSmartCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startClientButtonSmartCar)
                            .addComponent(simulateEmptyStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(severityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(severityButton)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void severityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityTextFieldActionPerformed

    private Integer userSeverity = null;
    private void severityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityButtonActionPerformed
        String input = severityTextField.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No severity entered. It will be randomly generated by the client.");
            makeStatusEmptyGUI = false;
            SmartCarClient.severityFromGUI = null; 
        } else {
            try {
                makeStatusEmptyGUI = false;
                int userSeverity = Integer.parseInt(input);

                if (userSeverity >= 1 && userSeverity <= 10) {
                    JOptionPane.showMessageDialog(this, "Number has been set: " + userSeverity);
                    SmartCarClient.severityFromGUI = userSeverity; 
                } else {
                    JOptionPane.showMessageDialog(this, "Number will be randomly generated");
                    SmartCarClient.severityFromGUI = null;
                }
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Number will be randomly generated");
                SmartCarClient.severityFromGUI = null;
            }
        }
    }//GEN-LAST:event_severityButtonActionPerformed

    public static boolean makeStatusEmptyGUI = false;
    private void simulateEmptyStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateEmptyStatusButtonActionPerformed
        if (!isServerRunning) {
            JOptionPane.showMessageDialog(this, "Cannot simulate empty string: Server is not running.");
            return;
        }
        
        makeStatusEmptyGUI = true;
        textAreaSmartCarClient.append("Status is empty now. ");
    }//GEN-LAST:event_simulateEmptyStatusButtonActionPerformed

    private void startServerButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning) {
            return; 
        }
        isServerRunning = true;
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarServer));
            System.setErr(getPrintStreamFor(textAreaSmartCarServer));
            try {
                SmartCarServer.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    private void startClientButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isServerRunning) {
            JOptionPane.showMessageDialog(this, "Cannot start client: Server is not running.");
            return;
        }

        textAreaSmartCarClient.append("Waiting for a respond...");
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarClient));
            System.setErr(getPrintStreamFor(textAreaSmartCarClient));
            try {
                SmartCarClient.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton severityButton;
    private javax.swing.JTextField severityTextField;
    private javax.swing.JButton simulateEmptyStatusButton;
    private javax.swing.JButton startClientButtonSmartCar;
    private javax.swing.JButton startServerButtonSmartCar;
    private javax.swing.JTextArea textAreaSmartCarClient;
    private javax.swing.JTextArea textAreaSmartCarServer;
    // End of variables declaration//GEN-END:variables
}
