package GUI;

import smartCarUnary.SmartCarClient;
import smartCarUnary.SmartCarServer;

import javax.swing.*;

public class GUISmartCar extends javax.swing.JPanel {
    private boolean isServerRunning = false;
    
public GUISmartCar() {
        initComponents();
    }

    private java.io.PrintStream getPrintStreamFor(JTextArea area) {
        return new java.io.PrintStream(new java.io.OutputStream() {
            private StringBuilder buffer = new StringBuilder();

            @Override
            public void write(int b) {
                if (b == '\n') {
                    String line = buffer.toString();
                    buffer.setLength(0);
                    SwingUtilities.invokeLater(() -> area.append(line + "\n"));
                } else {
                    buffer.append((char) b);
                }
            }
        }, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startServerButtonSmartCar = new javax.swing.JButton();
        startClientButtonSmartCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSmartCarServer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaSmartCarClient = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        startServerButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startServerButtonSmartCar.setText("Start Server");
        startServerButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonSmartCarActionPerformed(evt);
            }
        });

        startClientButtonSmartCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startClientButtonSmartCar.setText("Simulate Accident");
        startClientButtonSmartCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientButtonSmartCarActionPerformed(evt);
            }
        });

        textAreaSmartCarServer.setColumns(20);
        textAreaSmartCarServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarServer.setRows(5);
        jScrollPane1.setViewportView(textAreaSmartCarServer);

        textAreaSmartCarClient.setColumns(20);
        textAreaSmartCarClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaSmartCarClient.setRows(5);
        jScrollPane2.setViewportView(textAreaSmartCarClient);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Smart Car - Unary service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startClientButtonSmartCar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1008, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(456, 456, 456)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(startServerButtonSmartCar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(startServerButtonSmartCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(startClientButtonSmartCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startServerButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning) {
            return; 
        }
        isServerRunning = true;
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarServer));
            System.setErr(getPrintStreamFor(textAreaSmartCarServer));
            try {
                SmartCarServer.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    private void startClientButtonSmartCarActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isServerRunning) {
            SwingUtilities.invokeLater(() -> 
                textAreaSmartCarClient.append("Cannot start client: Server is not running.")
            );
        return;
    }
        
        new Thread(() -> {
            java.io.PrintStream originalOut = System.out;
            System.setOut(getPrintStreamFor(textAreaSmartCarClient));
            System.setErr(getPrintStreamFor(textAreaSmartCarClient));
            try {
                SmartCarClient.main(new String[]{});
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                System.setOut(originalOut);
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton startClientButtonSmartCar;
    private javax.swing.JButton startServerButtonSmartCar;
    private javax.swing.JTextArea textAreaSmartCarClient;
    private javax.swing.JTextArea textAreaSmartCarServer;
    // End of variables declaration//GEN-END:variables
}
