// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartwatchClientStream.proto

package smartwatchClientStream;

public final class SmartwatchClientStream {
  private SmartwatchClientStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StepDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartwatchClientStream.StepData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of steps recorded in a time interval
     * </pre>
     *
     * <code>int32 steps = 1;</code>
     */
    int getSteps();
  }
  /**
   * Protobuf type {@code smartwatchClientStream.StepData}
   */
  public  static final class StepData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartwatchClientStream.StepData)
      StepDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StepData.newBuilder() to construct.
    private StepData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StepData() {
      steps_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StepData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              steps_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartwatchClientStream.SmartwatchClientStream.StepData.class, smartwatchClientStream.SmartwatchClientStream.StepData.Builder.class);
    }

    public static final int STEPS_FIELD_NUMBER = 1;
    private int steps_;
    /**
     * <pre>
     * Number of steps recorded in a time interval
     * </pre>
     *
     * <code>int32 steps = 1;</code>
     */
    public int getSteps() {
      return steps_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (steps_ != 0) {
        output.writeInt32(1, steps_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (steps_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, steps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartwatchClientStream.SmartwatchClientStream.StepData)) {
        return super.equals(obj);
      }
      smartwatchClientStream.SmartwatchClientStream.StepData other = (smartwatchClientStream.SmartwatchClientStream.StepData) obj;

      boolean result = true;
      result = result && (getSteps()
          == other.getSteps());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getSteps();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartwatchClientStream.SmartwatchClientStream.StepData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartwatchClientStream.StepData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartwatchClientStream.StepData)
        smartwatchClientStream.SmartwatchClientStream.StepDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartwatchClientStream.SmartwatchClientStream.StepData.class, smartwatchClientStream.SmartwatchClientStream.StepData.Builder.class);
      }

      // Construct using smartwatchClientStream.SmartwatchClientStream.StepData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        steps_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepData_descriptor;
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepData getDefaultInstanceForType() {
        return smartwatchClientStream.SmartwatchClientStream.StepData.getDefaultInstance();
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepData build() {
        smartwatchClientStream.SmartwatchClientStream.StepData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepData buildPartial() {
        smartwatchClientStream.SmartwatchClientStream.StepData result = new smartwatchClientStream.SmartwatchClientStream.StepData(this);
        result.steps_ = steps_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartwatchClientStream.SmartwatchClientStream.StepData) {
          return mergeFrom((smartwatchClientStream.SmartwatchClientStream.StepData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartwatchClientStream.SmartwatchClientStream.StepData other) {
        if (other == smartwatchClientStream.SmartwatchClientStream.StepData.getDefaultInstance()) return this;
        if (other.getSteps() != 0) {
          setSteps(other.getSteps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartwatchClientStream.SmartwatchClientStream.StepData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartwatchClientStream.SmartwatchClientStream.StepData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int steps_ ;
      /**
       * <pre>
       * Number of steps recorded in a time interval
       * </pre>
       *
       * <code>int32 steps = 1;</code>
       */
      public int getSteps() {
        return steps_;
      }
      /**
       * <pre>
       * Number of steps recorded in a time interval
       * </pre>
       *
       * <code>int32 steps = 1;</code>
       */
      public Builder setSteps(int value) {
        
        steps_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of steps recorded in a time interval
       * </pre>
       *
       * <code>int32 steps = 1;</code>
       */
      public Builder clearSteps() {
        
        steps_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartwatchClientStream.StepData)
    }

    // @@protoc_insertion_point(class_scope:smartwatchClientStream.StepData)
    private static final smartwatchClientStream.SmartwatchClientStream.StepData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartwatchClientStream.SmartwatchClientStream.StepData();
    }

    public static smartwatchClientStream.SmartwatchClientStream.StepData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StepData>
        PARSER = new com.google.protobuf.AbstractParser<StepData>() {
      @java.lang.Override
      public StepData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StepData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StepData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StepData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartwatchClientStream.SmartwatchClientStream.StepData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StepSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartwatchClientStream.StepSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Total steps calculated by the server
     * </pre>
     *
     * <code>int32 totalSteps = 1;</code>
     */
    int getTotalSteps();

    /**
     * <pre>
     * Total calories calculated
     * </pre>
     *
     * <code>double caloriesBurned = 2;</code>
     */
    double getCaloriesBurned();

    /**
     * <pre>
     * Total active time in minutes
     * </pre>
     *
     * <code>int32 totalActiveTime = 3;</code>
     */
    int getTotalActiveTime();

    /**
     * <pre>
     * Advice depending on the level of the activity
     * </pre>
     *
     * <code>string feedback = 4;</code>
     */
    java.lang.String getFeedback();
    /**
     * <pre>
     * Advice depending on the level of the activity
     * </pre>
     *
     * <code>string feedback = 4;</code>
     */
    com.google.protobuf.ByteString
        getFeedbackBytes();
  }
  /**
   * Protobuf type {@code smartwatchClientStream.StepSummary}
   */
  public  static final class StepSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartwatchClientStream.StepSummary)
      StepSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StepSummary.newBuilder() to construct.
    private StepSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StepSummary() {
      totalSteps_ = 0;
      caloriesBurned_ = 0D;
      totalActiveTime_ = 0;
      feedback_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StepSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              totalSteps_ = input.readInt32();
              break;
            }
            case 17: {

              caloriesBurned_ = input.readDouble();
              break;
            }
            case 24: {

              totalActiveTime_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              feedback_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartwatchClientStream.SmartwatchClientStream.StepSummary.class, smartwatchClientStream.SmartwatchClientStream.StepSummary.Builder.class);
    }

    public static final int TOTALSTEPS_FIELD_NUMBER = 1;
    private int totalSteps_;
    /**
     * <pre>
     * Total steps calculated by the server
     * </pre>
     *
     * <code>int32 totalSteps = 1;</code>
     */
    public int getTotalSteps() {
      return totalSteps_;
    }

    public static final int CALORIESBURNED_FIELD_NUMBER = 2;
    private double caloriesBurned_;
    /**
     * <pre>
     * Total calories calculated
     * </pre>
     *
     * <code>double caloriesBurned = 2;</code>
     */
    public double getCaloriesBurned() {
      return caloriesBurned_;
    }

    public static final int TOTALACTIVETIME_FIELD_NUMBER = 3;
    private int totalActiveTime_;
    /**
     * <pre>
     * Total active time in minutes
     * </pre>
     *
     * <code>int32 totalActiveTime = 3;</code>
     */
    public int getTotalActiveTime() {
      return totalActiveTime_;
    }

    public static final int FEEDBACK_FIELD_NUMBER = 4;
    private volatile java.lang.Object feedback_;
    /**
     * <pre>
     * Advice depending on the level of the activity
     * </pre>
     *
     * <code>string feedback = 4;</code>
     */
    public java.lang.String getFeedback() {
      java.lang.Object ref = feedback_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feedback_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Advice depending on the level of the activity
     * </pre>
     *
     * <code>string feedback = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFeedbackBytes() {
      java.lang.Object ref = feedback_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feedback_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (totalSteps_ != 0) {
        output.writeInt32(1, totalSteps_);
      }
      if (caloriesBurned_ != 0D) {
        output.writeDouble(2, caloriesBurned_);
      }
      if (totalActiveTime_ != 0) {
        output.writeInt32(3, totalActiveTime_);
      }
      if (!getFeedbackBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, feedback_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (totalSteps_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, totalSteps_);
      }
      if (caloriesBurned_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, caloriesBurned_);
      }
      if (totalActiveTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalActiveTime_);
      }
      if (!getFeedbackBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, feedback_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartwatchClientStream.SmartwatchClientStream.StepSummary)) {
        return super.equals(obj);
      }
      smartwatchClientStream.SmartwatchClientStream.StepSummary other = (smartwatchClientStream.SmartwatchClientStream.StepSummary) obj;

      boolean result = true;
      result = result && (getTotalSteps()
          == other.getTotalSteps());
      result = result && (
          java.lang.Double.doubleToLongBits(getCaloriesBurned())
          == java.lang.Double.doubleToLongBits(
              other.getCaloriesBurned()));
      result = result && (getTotalActiveTime()
          == other.getTotalActiveTime());
      result = result && getFeedback()
          .equals(other.getFeedback());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTALSTEPS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalSteps();
      hash = (37 * hash) + CALORIESBURNED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCaloriesBurned()));
      hash = (37 * hash) + TOTALACTIVETIME_FIELD_NUMBER;
      hash = (53 * hash) + getTotalActiveTime();
      hash = (37 * hash) + FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + getFeedback().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartwatchClientStream.SmartwatchClientStream.StepSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartwatchClientStream.SmartwatchClientStream.StepSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartwatchClientStream.StepSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartwatchClientStream.StepSummary)
        smartwatchClientStream.SmartwatchClientStream.StepSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartwatchClientStream.SmartwatchClientStream.StepSummary.class, smartwatchClientStream.SmartwatchClientStream.StepSummary.Builder.class);
      }

      // Construct using smartwatchClientStream.SmartwatchClientStream.StepSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        totalSteps_ = 0;

        caloriesBurned_ = 0D;

        totalActiveTime_ = 0;

        feedback_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartwatchClientStream.SmartwatchClientStream.internal_static_smartwatchClientStream_StepSummary_descriptor;
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepSummary getDefaultInstanceForType() {
        return smartwatchClientStream.SmartwatchClientStream.StepSummary.getDefaultInstance();
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepSummary build() {
        smartwatchClientStream.SmartwatchClientStream.StepSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartwatchClientStream.SmartwatchClientStream.StepSummary buildPartial() {
        smartwatchClientStream.SmartwatchClientStream.StepSummary result = new smartwatchClientStream.SmartwatchClientStream.StepSummary(this);
        result.totalSteps_ = totalSteps_;
        result.caloriesBurned_ = caloriesBurned_;
        result.totalActiveTime_ = totalActiveTime_;
        result.feedback_ = feedback_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartwatchClientStream.SmartwatchClientStream.StepSummary) {
          return mergeFrom((smartwatchClientStream.SmartwatchClientStream.StepSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartwatchClientStream.SmartwatchClientStream.StepSummary other) {
        if (other == smartwatchClientStream.SmartwatchClientStream.StepSummary.getDefaultInstance()) return this;
        if (other.getTotalSteps() != 0) {
          setTotalSteps(other.getTotalSteps());
        }
        if (other.getCaloriesBurned() != 0D) {
          setCaloriesBurned(other.getCaloriesBurned());
        }
        if (other.getTotalActiveTime() != 0) {
          setTotalActiveTime(other.getTotalActiveTime());
        }
        if (!other.getFeedback().isEmpty()) {
          feedback_ = other.feedback_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartwatchClientStream.SmartwatchClientStream.StepSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartwatchClientStream.SmartwatchClientStream.StepSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int totalSteps_ ;
      /**
       * <pre>
       * Total steps calculated by the server
       * </pre>
       *
       * <code>int32 totalSteps = 1;</code>
       */
      public int getTotalSteps() {
        return totalSteps_;
      }
      /**
       * <pre>
       * Total steps calculated by the server
       * </pre>
       *
       * <code>int32 totalSteps = 1;</code>
       */
      public Builder setTotalSteps(int value) {
        
        totalSteps_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total steps calculated by the server
       * </pre>
       *
       * <code>int32 totalSteps = 1;</code>
       */
      public Builder clearTotalSteps() {
        
        totalSteps_ = 0;
        onChanged();
        return this;
      }

      private double caloriesBurned_ ;
      /**
       * <pre>
       * Total calories calculated
       * </pre>
       *
       * <code>double caloriesBurned = 2;</code>
       */
      public double getCaloriesBurned() {
        return caloriesBurned_;
      }
      /**
       * <pre>
       * Total calories calculated
       * </pre>
       *
       * <code>double caloriesBurned = 2;</code>
       */
      public Builder setCaloriesBurned(double value) {
        
        caloriesBurned_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total calories calculated
       * </pre>
       *
       * <code>double caloriesBurned = 2;</code>
       */
      public Builder clearCaloriesBurned() {
        
        caloriesBurned_ = 0D;
        onChanged();
        return this;
      }

      private int totalActiveTime_ ;
      /**
       * <pre>
       * Total active time in minutes
       * </pre>
       *
       * <code>int32 totalActiveTime = 3;</code>
       */
      public int getTotalActiveTime() {
        return totalActiveTime_;
      }
      /**
       * <pre>
       * Total active time in minutes
       * </pre>
       *
       * <code>int32 totalActiveTime = 3;</code>
       */
      public Builder setTotalActiveTime(int value) {
        
        totalActiveTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total active time in minutes
       * </pre>
       *
       * <code>int32 totalActiveTime = 3;</code>
       */
      public Builder clearTotalActiveTime() {
        
        totalActiveTime_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object feedback_ = "";
      /**
       * <pre>
       * Advice depending on the level of the activity
       * </pre>
       *
       * <code>string feedback = 4;</code>
       */
      public java.lang.String getFeedback() {
        java.lang.Object ref = feedback_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          feedback_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Advice depending on the level of the activity
       * </pre>
       *
       * <code>string feedback = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFeedbackBytes() {
        java.lang.Object ref = feedback_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          feedback_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Advice depending on the level of the activity
       * </pre>
       *
       * <code>string feedback = 4;</code>
       */
      public Builder setFeedback(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        feedback_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Advice depending on the level of the activity
       * </pre>
       *
       * <code>string feedback = 4;</code>
       */
      public Builder clearFeedback() {
        
        feedback_ = getDefaultInstance().getFeedback();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Advice depending on the level of the activity
       * </pre>
       *
       * <code>string feedback = 4;</code>
       */
      public Builder setFeedbackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        feedback_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartwatchClientStream.StepSummary)
    }

    // @@protoc_insertion_point(class_scope:smartwatchClientStream.StepSummary)
    private static final smartwatchClientStream.SmartwatchClientStream.StepSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartwatchClientStream.SmartwatchClientStream.StepSummary();
    }

    public static smartwatchClientStream.SmartwatchClientStream.StepSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StepSummary>
        PARSER = new com.google.protobuf.AbstractParser<StepSummary>() {
      @java.lang.Override
      public StepSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StepSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StepSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StepSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartwatchClientStream.SmartwatchClientStream.StepSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwatchClientStream_StepData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwatchClientStream_StepData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwatchClientStream_StepSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwatchClientStream_StepSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034smartwatchClientStream.proto\022\026smartwat" +
      "chClientStream\"\031\n\010StepData\022\r\n\005steps\030\001 \001(" +
      "\005\"d\n\013StepSummary\022\022\n\ntotalSteps\030\001 \001(\005\022\026\n\016" +
      "caloriesBurned\030\002 \001(\001\022\027\n\017totalActiveTime\030" +
      "\003 \001(\005\022\020\n\010feedback\030\004 \001(\t2j\n\021SmartWatchSer" +
      "vice\022U\n\ntrackSteps\022 .smartwatchClientStr" +
      "eam.StepData\032#.smartwatchClientStream.St" +
      "epSummary(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwatchClientStream_StepData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwatchClientStream_StepData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwatchClientStream_StepData_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_smartwatchClientStream_StepSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwatchClientStream_StepSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwatchClientStream_StepSummary_descriptor,
        new java.lang.String[] { "TotalSteps", "CaloriesBurned", "TotalActiveTime", "Feedback", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
